version: "3.1"
services:

  h2:
    build: ./h2
    container_name: h2
    ports:
      - "8082:8082"
      - "9082:9082"    
    volumes:
      - ./h2/data:/usr/lib/h2


  ontop:
    build: ./endpoint
    container_name: ontop
    ports:
      - "8080:8080"
